import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./loginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./logoutBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="header">
          <Link href="/">홈</Link>
          <Link href="/list">리스트</Link>
          <Link href="/signup">회원가입</Link>
          {session ? <LogoutBtn /> : <LoginBtn />}
        </div>
        {children}
      </body>
    </html>
  );
}
